Repository CeyLabs/BitcoinDeepaBot, pull requests merged in 2025-07, with the labels that each got.

#24 feat: add LKR amounts everywhere
  internal/telegram/balance.go
  internal/telegram/buttons.go
  internal/telegram/faucet.go
  internal/telegram/groups.go
  internal/telegram/inline_receive.go
  internal/telegram/inline_send.go
  internal/telegram/invoice.go
  internal/telegram/pay.go
  internal/telegram/send.go
  internal/telegram/tip.go
  internal/telegram/tipjar.go
  internal/thirdparty/coingecko.go
  translations/en.toml
Labels: enhancement, Review effort 3/5

#22 Add LKR to satoshi conversion command
  README.md
  botfather-setcommands.txt
  internal/telegram/buttons.go
  internal/telegram/handler.go
  internal/telegram/lkrsats.go
  internal/thirdparty/coingecko.go
  translations/cs.toml
  translations/de.toml
  translations/en.toml
  translations/es.toml
  translations/fi.toml
  translations/fr.toml
  translations/id.toml
  translations/it.toml
  translations/nl.toml
  translations/pl.toml
  translations/pt-br.toml
  translations/ru.toml
  translations/tr.toml
Labels: Review effort 2/5, codex

#27 Dev
  config.yaml.example
  examples/hmac_client.go
  internal/api/middleware.go
  internal/config.go
  main.go
Labels: Review effort 4/5, Possible security concern

#26 Add /convert command
  README.md
  botfather-setcommands.txt
  internal/telegram/convertsats.go
  internal/telegram/handler.go
  translations/de.toml
  translations/en.toml
  translations/es.toml
  translations/it.toml
  translations/nl.toml
Labels: Review effort 2/5, codex

#31 feat: Add thousands separator to sat amounts
  internal/telegram/api_approval.go
  internal/telegram/balance.go
  internal/telegram/error_logger.go
  internal/telegram/faucet.go
  internal/telegram/shop.go
  internal/telegram/shop_helpers.go
  internal/telegram/ticket.go
  internal/telegram/tipjar.go
  internal/telegram/tooltip.go
  internal/telegram/transactions.go
  internal/thirdparty/coingecko.go
  internal/utils/number_format.go
Labels: Review effort 2/5, codex

#32 fix: Add sat formatting to missed templates
  internal/api/admin/pending_transactions.go
  internal/api/send.go
  internal/lnbits/webhook/webhook.go
  internal/lnurl/lnurl.go
  internal/telegram/amounts.go
  internal/telegram/api_approval.go
  internal/telegram/convertsats.go
  internal/telegram/error_logger.go
  internal/telegram/groups.go
  internal/telegram/lkrsats.go
  internal/telegram/lnurl-pay.go
  internal/telegram/lnurl-withdraw.go
  internal/utils/number_format.go
  translations/cs.toml
  translations/de.toml
  translations/en.toml
  translations/es.toml
  translations/fi.toml
  translations/fr.toml
  translations/id.toml
  translations/it.toml
  translations/nl.toml
  translations/pl.toml
  translations/pt-br.toml
  translations/ru.toml
  translations/tr.toml
Labels: Review effort 3/5

#37 feat: Refactor API to use wallet-based HMAC security
  config.yaml.example
  internal/api/middleware.go
  internal/api/pending_transaction.go
  internal/api/send.go
  internal/api/send_config.go
  internal/config.go
  main.go
Labels: Review effort 4/5, Possible security concern
